
import { CropType, GrowthStage, CropDataset, Language, SoilType, SoilProfile, Region } from './types';

export const REGIONS: Region[] = [
  {
    id: 'vidarbha',
    name: 'Vidarbha',
    hindiName: 'विदर्भ',
    marathiName: 'विदर्भ',
    state: 'Maharashtra',
    defaultSoil: SoilType.BLACK,
    bounds: { minLat: 18.5, maxLat: 21.5, minLng: 76.0, maxLng: 80.5 }
  },
  {
    id: 'indo-gangetic',
    name: 'Indo-Gangetic Plains',
    hindiName: 'सिंधु-गंगा का मैदान',
    marathiName: 'सिंधु-गंगा मैदान',
    state: 'North India',
    defaultSoil: SoilType.ALLUVIAL,
    bounds: { minLat: 23.0, maxLat: 31.0, minLng: 74.0, maxLng: 88.0 }
  },
  {
    id: 'western-ghats',
    name: 'Western Ghats',
    hindiName: 'पश्चिमी घाट',
    marathiName: 'पश्चिम घाट',
    state: 'South West India',
    defaultSoil: SoilType.LATRITE,
    bounds: { minLat: 8.0, maxLat: 18.0, minLng: 73.0, maxLng: 77.0 }
  }
];

export const SOIL_PROFILES: Record<SoilType, SoilProfile> = {
  [SoilType.ALLUVIAL]: {
    type: SoilType.ALLUVIAL,
    name: 'Alluvial Soil',
    hindiName: 'जलोढ़ मिट्टी',
    marathiName: 'गाळाची मृदा',
    waterRetention: 'High',
    drainage: 'Good to Moderate',
    fertility: 'Highly Fertile',
    actionTips: ['Ideal for Rice and Wheat.', 'Maintain organic matter.', 'Check for Nitrogen levels.']
  },
  [SoilType.BLACK]: {
    type: SoilType.BLACK,
    name: 'Black Soil',
    hindiName: 'काली मिट्टी',
    marathiName: 'काळी मृदा (रेगूर)',
    waterRetention: 'High',
    drainage: 'Poor when wet',
    fertility: 'Rich in Potash & Lime',
    actionTips: ['Perfect for Cotton.', 'Deep cracks help in aeration.', 'Avoid over-irrigation.']
  },
  [SoilType.RED]: {
    type: SoilType.RED,
    name: 'Red Soil',
    hindiName: 'लाल मिट्टी',
    marathiName: 'तांबडी मृदा',
    waterRetention: 'Low',
    drainage: 'Excellent',
    fertility: 'Needs Fertilization',
    actionTips: ['Suitable for Pulses.', 'Requires more frequent watering.', 'Use more compost.']
  },
  [SoilType.LATRITE]: {
    type: SoilType.LATRITE,
    name: 'Laterite Soil',
    hindiName: 'लैटेराइट मिट्टी',
    marathiName: 'जांभी मृदा',
    waterRetention: 'Medium',
    drainage: 'Fast',
    fertility: 'Low (Acidic)',
    actionTips: ['Good for Cashew/Vegetables.', 'Add lime to reduce acidity.', 'Intensive manuring needed.']
  },
  [SoilType.SANDY]: {
    type: SoilType.SANDY,
    name: 'Sandy Soil',
    hindiName: 'रेतीली मिट्टी',
    marathiName: 'रेताड मृदा',
    waterRetention: 'Low',
    drainage: 'Excessive',
    fertility: 'Very Low',
    actionTips: ['Frequent irrigation required.', 'Use drip irrigation.', 'High leaching risk for fertilizer.']
  }
};

export const CROP_DATASETS: Record<CropType, CropDataset> = {
  [CropType.RICE]: {
    name: 'Rice', hindiName: 'चावल (धान)', marathiName: 'भात (धान)',
    advisories: {
      [GrowthStage.SOWING]: { stage: GrowthStage.SOWING, fertilizer: 'Zinc Sulphate (10kg/acre)', pestAlert: 'Stem borer nursery', irrigation: 'Moist only', tips: ['Seed treatment'] },
      [GrowthStage.VEGETATIVE]: { stage: GrowthStage.VEGETATIVE, fertilizer: 'Urea (25kg/acre)', pestAlert: 'Leaf folder', irrigation: '3cm standing water', tips: ['Weed check'] },
      [GrowthStage.FLOWERING]: { stage: GrowthStage.FLOWERING, fertilizer: 'Potash (15kg/acre)', pestAlert: 'Plant hopper', irrigation: 'Keep constant', tips: ["Don't spray now"] },
      [GrowthStage.MATURITY]: { stage: GrowthStage.MATURITY, fertilizer: 'None', pestAlert: 'Discoloration', irrigation: 'Drain 10 days early', tips: ['Bird watch'] },
      [GrowthStage.HARVEST]: { stage: GrowthStage.HARVEST, fertilizer: 'None', pestAlert: 'None', irrigation: 'Dry', tips: ['80% golden grain'] }
    }
  },
  [CropType.WHEAT]: {
    name: 'Wheat', hindiName: 'गेहूं', marathiName: 'गहू',
    advisories: {
      [GrowthStage.SOWING]: { stage: GrowthStage.SOWING, fertilizer: 'DAP (50kg/acre)', pestAlert: 'Termite', irrigation: 'CRI Stage (21 days)', tips: ['Level field'] },
      [GrowthStage.VEGETATIVE]: { stage: GrowthStage.VEGETATIVE, fertilizer: 'Urea (40kg/acre)', pestAlert: 'Aphids', irrigation: 'Constant moisture', tips: ['Inter-culture'] },
      [GrowthStage.FLOWERING]: { stage: GrowthStage.FLOWERING, fertilizer: 'None', pestAlert: 'Rust', irrigation: 'No stress', tips: ['Check cool temp'] },
      [GrowthStage.MATURITY]: { stage: GrowthStage.MATURITY, fertilizer: 'None', pestAlert: 'None', irrigation: 'Stop watering', tips: ['Grain hardens'] },
      [GrowthStage.HARVEST]: { stage: GrowthStage.HARVEST, fertilizer: 'None', pestAlert: 'None', irrigation: 'Dry', tips: ['Store in dry'] }
    }
  },
  [CropType.MAIZE]: {
    name: 'Maize', hindiName: 'मक्का', marathiName: 'मका',
    advisories: {
      [GrowthStage.SOWING]: { stage: GrowthStage.SOWING, fertilizer: 'NPK 12:32:16', pestAlert: 'Armyworm', irrigation: 'Pre-sow', tips: ['60cm gap'] },
      [GrowthStage.VEGETATIVE]: { stage: GrowthStage.VEGETATIVE, fertilizer: 'Urea side', pestAlert: 'Stem borer', irrigation: 'Avoid logging', tips: ['Earthing'] },
      [GrowthStage.FLOWERING]: { stage: GrowthStage.FLOWERING, fertilizer: 'None', pestAlert: 'Silk loss', irrigation: 'Critical', tips: ['Tasseling'] },
      [GrowthStage.MATURITY]: { stage: GrowthStage.MATURITY, fertilizer: 'None', pestAlert: 'Ear rot', irrigation: 'Low', tips: ['Black layer'] },
      [GrowthStage.HARVEST]: { stage: GrowthStage.HARVEST, fertilizer: 'None', pestAlert: 'None', irrigation: 'Dry', tips: ['<20% moisture'] }
    }
  },
  [CropType.COTTON]: {
    name: 'Cotton', hindiName: 'कपास', marathiName: 'कापूस',
    advisories: {
      [GrowthStage.SOWING]: { stage: GrowthStage.SOWING, fertilizer: 'Phosphorus', pestAlert: 'Sucking pests', irrigation: 'Gap fill', tips: ['Seed treat'] },
      [GrowthStage.VEGETATIVE]: { stage: GrowthStage.VEGETATIVE, fertilizer: 'Nitrogen split', pestAlert: 'Whitefly', irrigation: '20 days', tips: ['Weeding'] },
      [GrowthStage.FLOWERING]: { stage: GrowthStage.FLOWERING, fertilizer: 'DAP spray', pestAlert: 'Bollworm', irrigation: 'Regular', tips: ['Square form'] },
      [GrowthStage.MATURITY]: { stage: GrowthStage.MATURITY, fertilizer: 'None', pestAlert: 'Pink bollworm', irrigation: 'Stop', tips: ['Boll opens'] },
      [GrowthStage.HARVEST]: { stage: GrowthStage.HARVEST, fertilizer: 'None', pestAlert: 'None', irrigation: 'None', tips: ['Morning pick'] }
    }
  },
  [CropType.SUGARCANE]: {
    name: 'Sugarcane', hindiName: 'गन्ना', marathiName: 'ऊस',
    advisories: {
      [GrowthStage.SOWING]: { stage: GrowthStage.SOWING, fertilizer: 'Compost basal', pestAlert: 'Termites', irrigation: 'Light', tips: ['Setts check'] },
      [GrowthStage.VEGETATIVE]: { stage: GrowthStage.VEGETATIVE, fertilizer: 'Urea+Potash', pestAlert: 'Top borer', irrigation: 'Weekly', tips: ['Mulching'] },
      [GrowthStage.FLOWERING]: { stage: GrowthStage.FLOWERING, fertilizer: 'None', pestAlert: 'Pyrilla', irrigation: '10 days', tips: ['Propping'] },
      [GrowthStage.MATURITY]: { stage: GrowthStage.MATURITY, fertilizer: 'None', pestAlert: 'None', irrigation: 'Stop 1mo pre', tips: ['Brix check'] },
      [GrowthStage.HARVEST]: { stage: GrowthStage.HARVEST, fertilizer: 'None', pestAlert: 'None', irrigation: 'None', tips: ['Sharp cut'] }
    }
  },
  [CropType.PULSES]: {
    name: 'Pulses', hindiName: 'दालें', marathiName: 'कडधान्य',
    advisories: {
      [GrowthStage.SOWING]: { stage: GrowthStage.SOWING, fertilizer: 'Rhizobium', pestAlert: 'Wilt', irrigation: 'Pre-sow', tips: ['Deep sow'] },
      [GrowthStage.VEGETATIVE]: { stage: GrowthStage.VEGETATIVE, fertilizer: 'DAP 2%', pestAlert: 'Pod borer', irrigation: 'Low', tips: ['Nipping'] },
      [GrowthStage.FLOWERING]: { stage: GrowthStage.FLOWERING, fertilizer: 'Boron', pestAlert: 'Thrips', irrigation: 'Avoid heavy', tips: ['Bloom peak'] },
      [GrowthStage.MATURITY]: { stage: GrowthStage.MATURITY, fertilizer: 'None', pestAlert: 'None', irrigation: 'None', tips: ['Brown pods'] },
      [GrowthStage.HARVEST]: { stage: GrowthStage.HARVEST, fertilizer: 'None', pestAlert: 'None', irrigation: 'None', tips: ['Sun dry'] }
    }
  },
  [CropType.VEGETABLES]: {
    name: 'Vegetables', hindiName: 'सब्जियां', marathiName: 'भाजीपाला',
    advisories: {
      [GrowthStage.SOWING]: { stage: GrowthStage.SOWING, fertilizer: 'Compost', pestAlert: 'Damping off', irrigation: 'Sprinkle', tips: ['Nursery cover'] },
      [GrowthStage.VEGETATIVE]: { stage: GrowthStage.VEGETATIVE, fertilizer: 'NPK spray', pestAlert: 'Fruit borer', irrigation: 'Frequent', tips: ['Staking'] },
      [GrowthStage.FLOWERING]: { stage: GrowthStage.FLOWERING, fertilizer: 'Micros', pestAlert: 'Whitefly', irrigation: 'Regular', tips: ['Pollination'] },
      [GrowthStage.MATURITY]: { stage: GrowthStage.MATURITY, fertilizer: 'None', pestAlert: 'None', irrigation: 'Moderate', tips: ['Color change'] },
      [GrowthStage.HARVEST]: { stage: GrowthStage.HARVEST, fertilizer: 'None', pestAlert: 'None', irrigation: 'None', tips: ['Morning harvest'] }
    }
  }
};

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    home: 'Home',
    crops: 'Crops',
    soil: 'Soil',
    insights: '48 Hours',
    settings: 'Settings',
    profile: 'Profile',
    createAccount: 'Create Account',
    phone: 'Phone Number',
    village: 'Village / Location',
    experience: 'Farming Experience',
    getStarted: 'Get Started',
    welcome: 'Welcome to AgriSynch',
    editProfile: 'Edit Profile',
    saveProfile: 'Save Profile',
    actionCenter: 'Action Center',
    myFields: 'My Fields',
    offlineStatus: 'Offline Ready',
    syncStatus: 'Sync Status',
    registerCrop: 'Register Crop',
    nickname: 'Field Nickname',
    farmerNameLabel: 'Full Name',
    sowingDate: 'Sowing Date',
    soilType: 'Soil Type',
    region: 'Region',
    save: 'Register',
    fertilizer: 'Fertilizer',
    irrigation: 'Irrigation',
    pest: 'Pest Risk',
    tips: 'Action Tips',
    todayAdvice: "Today's Advice",
    soilIntelligence: 'Soil Intelligence',
    noCrops: 'No crops added.',
    lastSync: 'Updated',
    diagnostics: 'Diagnostics',
    askAI: 'Ask AI Expert',
    noActions: 'No immediate actions needed.',
    weatherSnapshot: 'Weather Forecast',
    insights48h: '48-Hour Insights',
    detectLocation: 'Detect Location',
    locationFound: 'Region Detected',
    manualSelect: 'Manual Selection',
    searching: 'Locating...',
    retention: 'Retention',
    fertility: 'Fertility',
    appearance: 'Appearance',
    accessibility: 'Accessibility',
    dataControl: 'Data Control',
    alerts: 'Alerts',
    usageMode: 'Usage Mode',
    privacy: 'Privacy',
    help: 'Help',
    about: 'About AgriSynch',
    theme: 'Theme',
    simpleMode: 'Simple Mode',
    advancedMode: 'Advanced Mode',
    highContrast: 'High Contrast',
    haptics: 'Haptic Feedback',
    criticalOnly: 'Critical Alerts Only',
    reminderTime: 'Reminder Time',
    clearCache: 'Clear Cache',
    recompute: 'Recompute Advice',
    clearConfirm: 'Are you sure? This cleans advisory history.',
    aboutAgriSynch: 'AgriSynch is a rural-first platform built to secure farm intelligence locally. No internet required for daily farm decisions.',
    supportedLangs: 'Supported Languages'
  },
  [Language.HINDI]: {
    home: 'होम',
    crops: 'फसलें',
    soil: 'मिट्टी',
    insights: '४८ घंटे',
    settings: 'सेटिंग्स',
    profile: 'प्रोफ़ाइल',
    createAccount: 'खाता बनाएँ',
    phone: 'फ़ोन नंबर',
    village: 'गाँव / स्थान',
    experience: 'खेती का अनुभव',
    getStarted: 'शुरू करें',
    welcome: 'AgriSynch में आपका स्वागत है',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    actionCenter: 'एक्शन सेंटर',
    myFields: 'मेरे खेत',
    offlineStatus: 'ऑफ़लाइन तैयार',
    syncStatus: 'सिंक स्थिति',
    registerCrop: 'फसल पंजीकृत करें',
    nickname: 'खेत का नाम',
    farmerNameLabel: 'पूरा नाम',
    sowingDate: 'बुवाई की तारीख',
    soilType: 'मिट्टी का प्रकार',
    region: 'क्षेत्र',
    save: 'पंजीकृत करें',
    fertilizer: 'उर्वरक',
    irrigation: 'सिंचाई',
    pest: 'कीट जोखिम',
    tips: 'कृती सुझाव',
    todayAdvice: 'आज की सलाह',
    soilIntelligence: 'मिट्टी की जानकारी',
    noCrops: 'कोई फसल नहीं जोड़ी गई।',
    lastSync: 'अपडेट किया गया',
    diagnostics: 'स्मार्ट निदान',
    askAI: 'विशेषज्ञ AI',
    noActions: 'कोई तत्काल कार्रवाई की आवश्यकता नहीं है।',
    weatherSnapshot: 'मौसम का पूर्वानुमान',
    insights48h: '४८ घंटे के सुझाव',
    detectLocation: 'स्थान पहचानें',
    locationFound: 'क्षेत्र पहचाना गया',
    manualSelect: 'मैनुअल चयन',
    searching: 'खोज रहे हैं...',
    retention: 'जल धारण',
    fertility: 'उर्वरता',
    appearance: 'दिखावट',
    accessibility: 'अभिगम्यता',
    dataControl: 'डेटा नियंत्रण',
    alerts: 'अलर्ट',
    usageMode: 'उपयोग मोड',
    privacy: 'गोपनीयता',
    help: 'सहायता',
    about: 'AgriSynch के बारे में',
    theme: 'थीम',
    simpleMode: 'सरल मोड',
    advancedMode: 'उन्नत मोड',
    highContrast: 'उच्च कंट्रास्ट',
    haptics: 'हॅप्टिक फीडबैक',
    criticalOnly: 'केवल महत्वपूर्ण अलर्ट',
    reminderTime: 'रिमाइंडर का समय',
    clearCache: 'कैश साफ करें',
    recompute: 'सुझावों की गणना करें',
    clearConfirm: 'क्या आप सुनिश्चित हैं? यह इतिहास साफ़ करता है।',
    aboutAgriSynch: 'AgriSynch एक ग्रामीण-प्रथम प्लेटफ़ॉर्म है जो स्थानीय रूप से कृषि जानकारी सुरक्षित रखने के लिए बनाया गया है।',
    supportedLangs: 'समर्थित भाषाएँ'
  },
  [Language.MARATHI]: {
    home: 'मुख्य',
    crops: 'पिके',
    soil: 'मृदा',
    insights: '४८ तास',
    settings: 'सेटिंग्ज',
    profile: 'प्रोफाइल',
    createAccount: 'खाते तयार करा',
    phone: 'फोन नंबर',
    village: 'गाव / स्थान',
    experience: 'शेतीचा अनुभव',
    getStarted: 'सुरुवात करा',
    welcome: 'AgriSynch मध्ये आपले स्वागत आहे',
    editProfile: 'प्रोफाइल संपादित करा',
    saveProfile: 'प्रोफाइल जतन करा',
    actionCenter: 'कृती केंद्र',
    myFields: 'माझी शेते',
    offlineStatus: 'ऑफलाइन तयार',
    syncStatus: 'सिंक स्थिती',
    registerCrop: 'पिकाची नोंदणी',
    nickname: 'शेत नाव',
    farmerNameLabel: 'पूर्ण नाव',
    sowingDate: 'पेरणीची तारीख',
    soilType: 'मृदा प्रकार',
    region: 'प्रदेश',
    save: 'नोंदणी करा',
    fertilizer: 'खत',
    irrigation: 'सिंचन',
    pest: 'कीड धोका',
    tips: 'कृती टिप्स',
    todayAdvice: 'आजचा सल्ला',
    soilIntelligence: 'मृदा माहिती',
    noCrops: 'कोणतेही पीक नाही.',
    lastSync: 'अपडेट झाले',
    diagnostics: 'स्मार्ट निदान',
    askAI: 'तज्ञ AI',
    noActions: 'कोणत्याही त्वरित कृतीची गरज नाही.',
    weatherSnapshot: 'हवामानाचा अंदाज',
    insights48h: '४८ तासांचे सल्ले',
    detectLocation: 'स्थान ओळखा',
    locationFound: 'प्रदेश ओळखला',
    manualSelect: 'मॅन्युअल निवड',
    searching: 'शोधत आहे...',
    retention: 'पाणी साठवण',
    fertility: 'सुपीकता',
    appearance: 'स्वरुप',
    accessibility: 'अभिगम्यता',
    dataControl: 'डेटा नियंत्रण',
    alerts: 'सूचना',
    usageMode: 'वापर मोड',
    privacy: 'गोपनीयता',
    help: 'मदत',
    about: 'AgriSynch बद्दल',
    theme: 'थीम',
    simpleMode: 'सोपा मोड',
    advancedMode: 'प्रगत मोड',
    highContrast: 'हाय कॉन्ट्रास्ट',
    haptics: 'हॅप्टिक फीडबॅक',
    criticalOnly: 'केवळ महत्वाच्या सूचना',
    reminderTime: 'रिमाइंडर वेळ',
    clearCache: 'कॅश साफ करा',
    recompute: 'सल्ल्यांची गणना करा',
    clearConfirm: 'तुम्हाला खात्री आहे का? यामुळे जुना इतिहास साफ होईल.',
    aboutAgriSynch: 'AgriSynch हे ग्रामीण भागातील शेतकऱ्यांसाठी स्थानिक पातळीवर कृषी माहिती सुरक्षित ठेवणारे व्यासपीठ आहे.',
    supportedLangs: 'समर्थित भाषा'
  }
};
